### ISSUE TITLE
400 Error on Task Creation - Enum Mismatch for Task Status

### ISSUE THREAD

**Issue by RezaBG** [RezaBG/TUDU_BE#42]
I’m facing an issue when trying to create a task via the API. The task creation fails with a 400 Bad Request error, and the message returned is:

"Invalid input value for enum taskstatus: 'PENDING'"

Current Progress:
	•	I’ve already implemented the conversion of the task status to lowercase before passing it to the database.
	•	The status is being converted to "pending", but the database still rejects it, as the enum only accepts lowercase values like "pending", "in-progress", or "completed".

Additional Notes:
	•	I’ve been working on fixing this issue for the TaskStatus enum and its case handling, but I’m stuck with this mismatch issue.
	•	I’m looking for guidance on resolving this or if I should consider refactoring the TaskStatus enum in the database or API.
	
<img width="1454" alt="Screenshot 2024-12-12 at 23 40 54" src="https://github.com/user-attachments/assets/712ab2ad-9d30-4a03-82f0-3c1f8644ce41" />

<img width="718" alt="image" src="https://github.com/user-attachments/assets/58f5150c-ae92-44e6-9de2-a1825d61e94c" />

**Comment by IshanRastogi** [comment]
Why is your `database enums` all `lowercase` ?? From the same code, I've `upper case` enums.
